name: Build and release on semantic versioning tags

on:
  push:
    branches:
      - main

jobs:
  analyze-tags:
    runs-on: ubuntu-latest
    outputs:
      prevTag: ${{ steps.previous-tag.outputs.tag }}
      curTag: ${{ steps.current-tag.outputs.current-version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Get new version number
        id: current-tag
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Get previous version number
        id: previous-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 0.0.0

  build:
    runs-on: ubuntu-latest
    needs: analyze-tags
    if: needs.analyze-tags.outputs.curTag != needs.analyze-tags.outputs.prevTag
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: latest
          run_install: true
      - name: Make sure tests are passing
        run: pnpm test
      - name: Build project
        id: build-process
        run: pnpm run build
      - name: Check on build failures
        if: steps.build-process.outcome != 'success'
        run: exit 1
      - name: Add tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          default_bump: false
          custom_tag: ${{ needs.analyze-tags.outputs.curTag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: './dist/RCRemote.html'
